name: Cypress running in parallel

on:
  workflow_dispatch:
    inputs: {}

defaults:
    run:
        shell: bash

jobs:
    cypress-paralel:
        strategy:
            matrix:
              split_index: [1, 2]
        name: Cypress
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Docker GitHub auth
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: token
            password: ${{ secrets.WRITE_PACKAGES_TOKEN }}

        - name: Cache Docker images.
          uses: ScribeMD/docker-cache@0.5.0
          with:
            key: docker-${{ runner.os }}-${{ github.ref_name }}

        - name: Run copmose
          run: |
              docker compose up -d

        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Get npm cache directory
          id: npm-cache-dir
          shell: bash
          run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

        - uses: actions/cache@v3
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
            path: ${{ steps.npm-cache-dir.outputs.dir }}
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - run: npm ci

        - name: Run cypress
          env:
            CYPRESS_SPLIT_INDEX: ${{ matrix.split_index }}
            CYPRESS_SPLIT: 2
            CYPRESS_NEXT_APP_URL: http://next-app:3000
            CYPRESS_SPEC: cypress/e2e/**/*.cy.ts
          run: |
              docker compose run --rm cypress