name: Cypress running in parallel

on:
  workflow_dispatch:
    inputs: {}

defaults:
    run:
        shell: bash

jobs:
    cypress-paralel:
        strategy:
            matrix:
              split_index: [1, 2]
        name: Cypress
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Build docker imaag
          run: |
            docker compose build

        - name: Run copmose
          run: |
              docker compose up -d

        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - run: npm ci

        - name: Run cypress
          env:
            CYPRESS_SPLIT_INDEX: ${{ matrix.split_index }}
            CYPRESS_SPLIT: 2
            CYPRESS_NEXT_APP_URL: http://next-app:3000
            CYPRESS_SPEC: cypress/e2e/**/*.cy.ts
          run: |
              docker compose run --rm cypress