name: Cypress runnning serially

on:
  workflow_dispatch:
    inputs: {}

defaults:
    run:
        shell: bash

jobs:
    cypress-serial:
        name: Cypress
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Build docker imaag
          run: |
            docker compose build

        - name: Run copmose
          run: |
              docker compose up -d

        - uses: actions/setup-node@v4
          with:
            node-version: 20

        - run: npm ci

        - name: Run cypress
          run: |
              docker compose run --rm cypress